import type { Project, MoreProject, Experience, SkillNode, Stat, EngineeringExpertise, Service, Testimonial, Highlight, HardwareSkill } from '@/types';

export const personal = {
  name: 'Chirag Shyani',
  firstName: 'Chirag',
  lastName: 'Shyani',
  title: 'Senior Flutter Developer & Technical Lead',
  roles: ['Mobile Engineering', 'AI Integration', 'Software Architecture'],
  tagline: '5+ YEARS BUILDING ENTERPRISE MOBILE & CROSS-PLATFORM PRODUCTS',
  about: [
    'Mobile applications.',
    'AI-powered experiences.',
    'SaaS platforms.',
    'Real-time systems.',
    'Hardware integrations.',
  ],
  email: 'chirag.shyani17@gmail.com',
  phone: '+91 8141526123',
  location: 'Surat, Gujarat, India',
  linkedin: 'https://linkedin.com/in/chirag-shiyani-717063245',
  github: 'https://github.com/chirag-12-mmax',
  portfolio: 'https://chirag-shyani-portfolio.web.app',
  resumeUrl: '/resume.html',
  cvUrl: '/cv.html',
  resumePdfUrl: '/resume.pdf',
  availability: ['Remote', 'Full-Time', 'Contract', 'Technical Co-Founder'],
  recruitMessage: 'Open to Senior Flutter Engineer, Flutter Technical Lead, and Flutter Mobile Engineer roles at product companies and enterprise teams.',
  responseTime: '< 24 hours',
  availabilityStatus: 'Available for new opportunities',
  aboutStory: `I'm not just a developer who writes code — I'm an engineer who solves business problems through software.

With over 5+ years of experience, I specialize in building scalable enterprise applications and seamlessly integrating modern AI services into production environments. Rather than building raw AI models or focusing on advanced Python development, my expertise lies in designing, developing, and shipping real-world applications that harness AI capabilities to deliver exceptional user experiences.

Today, I architect enterprise-grade applications that serve thousands of users across Android, iOS, Web, and Desktop — all from a single, meticulously crafted codebase. I've shipped 8+ published applications to the Play Store and App Store, built a construction marketplace that scaled to 100K+ downloads, and led technical teams through complex product cycles.

What drives me is the intersection of engineering excellence and real-world impact. Every architecture decision I make, every performance optimization I ship, and every team I lead is focused on one goal: building software that people rely on every day.`,
  aboutPillars: [
    { title: 'Architecture', description: 'Clean Architecture, MVVM, and scalable patterns that make codebases maintainable at scale.', icon: '📐' },
    { title: 'Leadership', description: 'Leading cross-functional teams through Agile sprints, code reviews, and mentoring junior developers.', icon: '👥' },
    { title: 'Product Mindset', description: 'Translating complex business requirements into intuitive, high-performing user experiences.', icon: '💡' },
    { title: 'Performance', description: 'Deep profiling, memory optimization, and rendering performance to deliver butter-smooth 60fps apps.', icon: '⚡' },
  ],
  specializations: [
    'Enterprise Application Development',
    'Cross-Platform Architecture',
    'Technical Team Leadership',
    'Flutter Mobile & Web & Desktop',
    'Firebase & Cloud Integration',
    'CI/CD & DevOps',
    'REST API & GraphQL Integration',
    'Payment Gateway Integration',
    'Agile Scrum Methodology',
  ],
};

export const stats: Stat[] = [
  { value: 5, suffix: '+', label: 'Years' },
  { value: 30, suffix: '+', label: 'Projects' },
  { value: 8, suffix: '+', label: 'Published Apps' },
  { value: 100, suffix: 'K+', label: 'Downloads' },
  { value: 4, suffix: '+', label: 'Devs Led' },
];

export { projects, featuredProjects } from '@/data/projects';

const _legacyProjects: Project[] = [
  {
    id: 'buildmart',
    index: '01',
    name: 'Magicrete BuildMart',
    title: 'Magicrete BuildMart',
    subtitle: 'Construction Marketplace',
    meta: '10 months · Play Store & App Store',
    coverImage: '/projects/buildmart.svg',
    shortDescription: 'Pan-India dealer/distributor construction marketplace with SQLite offline-first architecture, background ERP sync, and delta updates scaled to 100K+ downloads.',
    description:
      'Pan-India dealer/distributor marketplace with SQLite offline-first architecture, background ERP sync, and delta-update strategies for low-connectivity construction zones. Scaled to 100K+ Google Play downloads.',
    stack: ['Flutter', 'REST API', 'ERP Integration', 'SQLite', 'Offline Sync', 'Firebase'],
    metrics: '100K+ Downloads',
    category: 'enterprise',
    featured: true,
    role: 'Senior Flutter Developer',
    teamSize: '4 developers',
    timeline: '10 months',
    businessDomain: 'Construction',
    businessImpact: 'Scaled to 100K+ downloads on Google Play Store, digitizing procurement workflows for a major Indian construction materials brand.',
    problem: 'A major Indian construction brand needed to digitize their dealer/distributor network for product ordering and inventory management — many locations had poor connectivity.',
    solution: 'Engineered an offline-first marketplace with ERP integration, background sync for inventory operations, and a streamlined ordering workflow optimized for low-connectivity environments.',
    architecture: 'Offline-first with SQLite local cache, background ERP sync service, queue-based order processing, and delta sync for bandwidth optimization.',
    features: ['Enterprise Product Catalog', 'Dealer & Distributor Network', 'Order Management System', 'Inventory Tracking', 'Offline Data Sync', 'ERP Integration', 'Delivery Coordination'],
    challenges: [
      'Reliable operation in construction zones with poor connectivity',
      'Complex ERP integration with legacy enterprise systems',
      'Scaling to support 100K+ concurrent users across India',
    ],
    results: [
      { metric: 'Downloads', value: '100K+' },
      { metric: 'Data Usage', value: '-40%' },
      { metric: 'ERP Systems', value: '3+' },
    ],
    playStoreUrl: 'https://play.google.com/store/apps/details?id=com.instanceit.magicreteclients&hl=en_IN',
    appStoreUrl: 'https://apps.apple.com/in/app/magicrete-buildmart/id1459372257',
    floating: {
      size: 'large',
      depth: 'front',
      laneTop: '10%',
      direction: 1,
      duration: 21,
      initialProgress: 0.18,
      floatAmp: 10,
      tilt: 0.8,
    },
  },
  {
    id: 'pulpit',
    index: '02',
    name: 'Pulpit Mobility',
    title: 'Pulpit Mobility',
    subtitle: 'Enterprise Transportation',
    meta: '6 months · Lead Developer · 5+ Cities',
    coverImage: '/projects/pulpit.svg',
    shortDescription: 'Real-time ride booking with WebSocket live driver tracking, Google Maps geofencing, offline-resilient architecture, and multi-gateway payment processing across 5+ cities.',
    description:
      'Real-time ride booking with WebSocket live driver tracking, Google Maps geofencing, offline-resilient architecture, and multi-gateway payment processing (Razorpay & Apple Pay) across 5+ cities.',
    stack: ['Flutter', 'Firebase', 'Google Maps', 'WebSocket', 'Razorpay', 'Apple Pay', 'BLoC'],
    metrics: '5+ Cities · <500ms Latency',
    category: 'realtime',
    featured: true,
    role: 'Lead Flutter Developer',
    teamSize: '3 developers',
    timeline: '6 months',
    businessDomain: 'Transportation',
    businessImpact: 'Enabled real-time fleet coordination and secure ride transactions for transportation operations across multiple cities.',
    problem: 'Transportation companies needed a unified platform for real-time ride management, driver tracking, and payment processing — existing solutions were fragmented and unreliable in low-connectivity areas.',
    solution: 'Built a modular cross-platform app with WebSocket-powered live tracking, geofencing zones, and an offline-resilient architecture that maintains state during network drops.',
    architecture: 'Clean Architecture with BLoC state management, WebSocket layer for real-time updates, Google Maps integration with custom geofencing, and Firebase for auth/notifications.',
    features: ['Real-Time Ride Tracking', 'Geofencing & Maps Integration', 'Push Notification Architecture', 'Secure Payment Gateway Integration', 'Driver & Rider Authentication', 'Offline Data Resilience'],
    challenges: [
      'Maintaining real-time accuracy with unstable network connections',
      'Implementing geofencing with minimal battery drain',
      'Secure payment processing across multiple gateway providers',
    ],
    results: [
      { metric: 'Cities Covered', value: '5+' },
      { metric: 'Real-Time Latency', value: '<500ms' },
      { metric: 'Uptime', value: '99.5%' },
    ],
    playStoreUrl: 'https://play.google.com/store/apps/details?id=com.pulpit.travel_driver_pulpit&hl=en_IN',
    floating: {
      size: 'large',
      depth: 'front',
      laneTop: '50%',
      direction: -1,
      duration: 19,
      initialProgress: 0.45,
      floatAmp: 12,
      tilt: -0.9,
    },
  },
  {
    id: 'myrcloud',
    index: '03',
    name: 'MyRCloud Platform',
    title: 'MyRCloud Platform',
    subtitle: 'Multi-Platform HR Ecosystem',
    meta: '8 months · Android · iOS · Web',
    coverImage: '/projects/myrcloud.svg',
    shortDescription: 'True cross-platform recruitment ecosystem with HRMS integration, WebSocket notifications, and RBAC across Android, iOS, and Flutter Web from one codebase.',
    description:
      'True cross-platform recruitment ecosystem with HRMS integration, WebSocket real-time notifications, and role-based access control across Android, iOS, and Flutter Web from a single codebase.',
    stack: ['Flutter', 'Flutter Web', 'REST API', 'WebSocket', 'HRMS', 'RBAC'],
    metrics: '5K+ Candidates · 85% Shared Code',
    category: 'enterprise',
    featured: true,
    role: 'Lead Flutter Developer',
    teamSize: '3 developers',
    timeline: '8 months',
    businessDomain: 'Recruitment',
    businessImpact: 'Streamlined recruitment operations for enterprise HR teams by consolidating candidate management across mobile and web platforms.',
    problem: 'Enterprise HR teams needed a unified recruitment platform that works identically across mobile and web, with real-time candidate tracking and HRMS integration.',
    solution: 'Built a true cross-platform recruitment ecosystem using Flutter for Android, iOS, and Web with shared business logic, WebSocket-driven real-time notifications, and deep HRMS integration.',
    architecture: 'Shared core with platform-specific UI adaptations, WebSocket notification layer, RBAC middleware, and HRMS API bridge pattern.',
    features: ['Recruiter & Candidate Dashboards', 'HRMS Integration', 'Job Application Pipeline', 'Real-Time Notifications', 'Role-Based Access Control (RBAC)', 'Workflow Automation', 'Cross-Platform (Android, iOS, Web)'],
    challenges: [
      'Maintaining feature parity across mobile and web platforms',
      'Implementing role-based access control for enterprise security',
      'Real-time synchronization of candidate pipeline across devices',
    ],
    results: [
      { metric: 'Platforms', value: '3' },
      { metric: 'Candidates Served', value: '5K+' },
      { metric: 'Code Sharing', value: '85%' },
    ],
    liveUrl: 'https://myrcloud.com/candidates',
    floating: {
      size: 'wide',
      depth: 'middle',
      laneTop: '70%',
      direction: 1,
      duration: 26,
      initialProgress: 0.62,
      floatAmp: 9,
      tilt: 0.5,
    },
  },
  {
    id: 'living',
    index: '04',
    name: 'LIVING — Godrej',
    title: 'LIVING — Godrej',
    subtitle: 'Real Estate & Community',
    meta: '8 months · Android · iOS · Web',
    coverImage: '/projects/living.svg',
    shortDescription: 'Gated community management platform with QR visitor verification, gate security, maintenance requests, and real-time resident notifications.',
    description:
      'End-to-end real estate and gated community management platform with QR visitor verification, gate security, maintenance requests, and real-time notifications for enterprise property management.',
    stack: ['Flutter', 'Node.js', 'REST API', 'QR Verification', 'Push Notifications', 'BLoC'],
    metrics: '+60% Operational Efficiency',
    category: 'enterprise',
    featured: true,
    role: 'Lead Flutter Developer',
    teamSize: '3 developers',
    timeline: '8 months',
    businessDomain: 'Real Estate / Community Management',
    businessImpact: 'Digitized society management for gated communities, streamlining visitor verification and maintenance operations.',
    problem: 'Residential societies needed a digital platform to manage visitors, maintenance payments, and resident communication securely and efficiently.',
    solution: 'Built a full-stack platform with dedicated modules for residents, guards, and admins to ensure smooth society operations.',
    architecture: 'Clean Architecture with BLoC state management and Node.js backend integration.',
    features: ['Visitor Entry Management', 'Gate Security', 'Resident Management', 'Maintenance Requests', 'Complaint Management', 'Vehicle Management', 'Visitor QR Verification', 'Daily Services Booking'],
    challenges: [
      'Implementing fast and secure QR verification at gates',
      'Managing roles and permissions for diverse users',
      'Integrating real-time notifications for visitor entry',
    ],
    results: [
      { metric: 'Security', value: 'High' },
      { metric: 'Efficiency', value: '+60%' },
    ],
    floating: {
      size: 'medium',
      depth: 'middle',
      laneTop: '26%',
      direction: -1,
      duration: 25,
      initialProgress: 0.28,
      floatAmp: 10,
      tilt: -0.7,
    },
  },
  {
    id: 'nch-enterprise',
    index: '05',
    name: 'NCH Enterprise Solution',
    title: 'NCH Enterprise Solution',
    subtitle: 'Multi-Platform Business Management',
    meta: '8 months · Flutter Web · Windows Desktop',
    coverImage: '/projects/nch-enterprise.svg',
    shortDescription: 'Enterprise business management deployed on Flutter Web and Windows Desktop with multi-branch operations, GraphQL queries, RBAC, and analytics.',
    description:
      'Enterprise-grade business management software deployed across Flutter Web and Flutter Windows Desktop. Delivers centralized multi-branch operations, role-based access control, workflow automation, and analytics dashboards for large enterprise clients.',
    stack: ['Flutter Web', 'Flutter Desktop', 'GraphQL', 'REST API', 'RBAC', 'Analytics'],
    metrics: '-70% Reporting Time',
    category: 'desktop',
    featured: true,
    role: 'Lead Flutter Developer',
    teamSize: '3 developers',
    timeline: '8 months',
    businessDomain: 'Enterprise Management',
    businessImpact: 'Enabled centralized enterprise management across multiple business branches, significantly improving operational visibility and reducing reporting overhead.',
    problem: 'An enterprise client needed centralized management across multiple branches with role-based access, workflow automation, and analytics — but required both web and desktop deployment.',
    solution: 'Developed a single-codebase solution deployed on both Flutter Web and Windows Desktop, with GraphQL for efficient data queries and comprehensive RBAC for enterprise security.',
    architecture: 'Shared business logic with platform-adaptive UI, GraphQL API layer, RBAC middleware, and modular dashboard architecture.',
    features: ['Multi-Branch Operations Management', 'Role-Based User Permissions', 'Business Workflow Automation', 'Reporting & Analytics Dashboards', 'Centralized Data Management', 'Flutter Web Deployment', 'Flutter Windows Desktop Deployment'],
    challenges: [
      'Delivering consistent experience across web and native desktop',
      'Complex GraphQL schema for multi-branch data aggregation',
      'Enterprise-grade role-based access control implementation',
    ],
    results: [
      { metric: 'Platforms', value: '2' },
      { metric: 'Branches', value: 'Multi' },
      { metric: 'Reporting Time', value: '-70%' },
    ],
    floating: {
      size: 'portrait',
      depth: 'far',
      laneTop: '4%',
      direction: 1,
      duration: 34,
      initialProgress: 0.52,
      floatAmp: 6,
      tilt: 0.4,
    },
  },
  {
    id: 'sah-investment',
    index: '06',
    name: 'SAH Investment',
    title: 'SAH Investment',
    subtitle: 'Financial Management Application',
    meta: '6 months · Android · iOS',
    coverImage: '/projects/sah-investment.svg',
    shortDescription: 'Secure financial management application with portfolio tracking, investment analytics, real-time dashboards, and bank-grade data encryption.',
    description:
      'Secure investment and financial management application with portfolio tracking, investment analytics, transaction management, real-time dashboards, and financial reporting with bank-grade security.',
    stack: ['Flutter', 'Node.js', 'REST API', 'Data Analytics', 'Secure Auth', 'Encryption'],
    metrics: 'Bank-Grade Security',
    category: 'enterprise',
    featured: true,
    role: 'Flutter Developer',
    teamSize: '2 developers',
    timeline: '6 months',
    businessDomain: 'Finance',
    businessImpact: 'Provided users with comprehensive financial visibility and secure transaction management tools.',
    problem: 'Users lacked a consolidated view of their investments and required secure, real-time analytics for portfolio management.',
    solution: 'Engineered a highly secure financial dashboard with real-time tracking, intuitive data visualization, and secure backend integration.',
    architecture: 'MVVM architecture with secure local storage and encrypted API communication.',
    features: ['Investment Tracking', 'Portfolio Management', 'Real-time Analytics', 'Reports Dashboard', 'Secure Transactions', 'Push Notifications'],
    challenges: [
      'Ensuring bank-grade security for financial data',
      'Rendering complex charts and analytics smoothly',
      'Synchronizing real-time portfolio updates',
    ],
    results: [
      { metric: 'Security', value: 'Bank-Grade' },
      { metric: 'Analytics', value: 'Real-time' },
    ],
    floating: {
      size: 'small',
      depth: 'far',
      laneTop: '40%',
      direction: -1,
      duration: 36,
      initialProgress: 0.82,
      floatAmp: 8,
      tilt: -0.5,
    },
  },
  {
    id: 'zinghr',
    index: '07',
    name: 'ZingHR Onboarding',
    title: 'ZingHR Onboarding',
    subtitle: 'Enterprise HR Onboarding Platform',
    meta: '5 months · 1,000+ Users · Play Store & App Store',
    coverImage: '/projects/zinghr.svg',
    shortDescription: 'Enterprise HR digital onboarding mobile application with secure document workflows, digital policy acknowledgment, and enterprise SSO authentication.',
    description:
      'Enterprise-grade HR onboarding mobile application delivering seamless digital onboarding for new employees. Integrated secure document submission workflows, digital policy acknowledgment, custom enterprise authentication, and cross-platform mobile access.',
    stack: ['Flutter', 'Enterprise Authentication', 'REST API', 'Custom Plugins', 'Secure Document Management'],
    metrics: '1000+ Users · -50% Onboarding Time',
    category: 'enterprise',
    featured: true,
    role: 'Flutter Developer',
    teamSize: '2 developers',
    timeline: '5 months',
    businessDomain: 'Human Resources',
    businessImpact: 'Enabled enterprise HR operations to digitize onboarding workflows, supporting thousands of concurrent enterprise users at scale.',
    problem: 'Enterprise HR teams needed to digitize onboarding for thousands of concurrent new hires — paper-based processes were slow, error-prone, and couldn\'t scale.',
    solution: 'Built a secure digital onboarding app with document submission workflows, policy acknowledgment, enterprise SSO integration, and performance optimization for large concurrent user bases.',
    architecture: 'Enterprise authentication bridge, secure document management pipeline, custom Flutter plugins for native integrations, and performance-optimized rendering.',
    features: ['Digital Employee Onboarding', 'Secure Document Submission', 'Policy Acknowledgment Workflows', 'Enterprise Authentication Integration', 'Cross-Platform Mobile Support', 'Performance Optimization'],
    challenges: [
      'Enterprise SSO integration with custom authentication providers',
      'Secure document handling with compliance requirements',
      'Performance at scale with thousands of concurrent users',
    ],
    results: [
      { metric: 'Users at Scale', value: '1000+' },
      { metric: 'Onboarding Time', value: '-50%' },
      { metric: 'Platforms', value: '2' },
    ],
    playStoreUrl: 'https://play.google.com/store/apps/details?id=com.zinghr.onboarding&hl=en_IN',
    appStoreUrl: 'https://apps.apple.com/us/app/zinghr-onboarding/id1165774242',
    floating: {
      size: 'medium',
      depth: 'middle',
      laneTop: '16%',
      direction: -1,
      duration: 23,
      initialProgress: 0.72,
      floatAmp: 9,
      tilt: -0.8,
    },
  },
  {
    id: 'magicrete-sarthak',
    index: '08',
    name: 'Magicrete Sarthak',
    title: 'Magicrete Sarthak',
    subtitle: 'Enterprise Employee Engagement Platform',
    meta: '6 months · Android · iOS · +35% Engagement',
    coverImage: '/projects/magicrete-sarthak.svg',
    shortDescription: 'Enterprise engagement platform with loyalty rewards, training module management, gamification, attendance tracking, and business analytics.',
    description:
      'Comprehensive enterprise employee and channel partner engagement platform delivering loyalty programs, training module management, gamified rewards, attendance tracking, leave management, helpdesk ticketing, and business growth analytics.',
    stack: ['Flutter', 'REST API', 'Analytics Integration', 'Push Notifications', 'Provider'],
    metrics: '+35% Engagement',
    category: 'enterprise',
    featured: true,
    role: 'Flutter Developer',
    teamSize: '2 developers',
    timeline: '6 months',
    businessDomain: 'Construction',
    businessImpact: 'Increased employee and partner engagement for a large enterprise by providing a unified digital platform for HR and channel operations.',
    problem: 'A large enterprise needed a unified platform for employee engagement, partner loyalty, training management, and HR operations — existing systems were fragmented across multiple tools.',
    solution: 'Built a comprehensive engagement platform with gamified rewards, attendance/leave management, training modules, helpdesk ticketing, and analytics dashboards in a single app.',
    architecture: 'Modular feature architecture with Provider state management, analytics event tracking layer, and REST API abstraction for multi-backend integration.',
    features: ['Loyalty & Rewards Programs', 'Employee Attendance & Leave Management', 'Training Module Management', 'Helpdesk Ticketing System', 'Analytics Dashboard', 'Channel Partner Engagement', 'Business Growth Tracking'],
    challenges: [
      'Consolidating 6+ separate HR/engagement workflows into one app',
      'Implementing gamification without impacting app performance',
      'Real-time analytics dashboard with complex data aggregation',
    ],
    results: [
      { metric: 'Workflows Unified', value: '6+' },
      { metric: 'Platforms', value: '2' },
      { metric: 'Engagement', value: '+35%' },
    ],
    playStoreUrl: 'https://play.google.com/store/apps/details?id=com.instanceit.magicretesarthak&hl=en_IN',
    appStoreUrl: 'https://apps.apple.com/in/app/magicrete-sarthak/id1585927876',
    floating: {
      size: 'small',
      depth: 'far',
      laneTop: '82%',
      direction: 1,
      duration: 38,
      initialProgress: 0.35,
      floatAmp: 7,
      tilt: 0.6,
    },
  },
  {
    id: 'dg-ferry',
    index: '09',
    name: 'DG Ferry Agent Booking',
    title: 'DG Ferry Agent Booking',
    subtitle: 'Maritime Enterprise Platform',
    meta: '5 months · Offline-First · Play Store & App Store',
    coverImage: '/projects/dg-ferry.svg',
    shortDescription: 'Maritime communication and operations platform with encrypted channels, agent booking workflows, and offline-first synchronization for use at sea.',
    description:
      'Enterprise-grade maritime communication and operations platform enabling secure information exchange, business workflow management, and operational coordination for the marine industry. Multi-layer secure authentication and encrypted communication channels.',
    stack: ['Flutter', 'REST API', 'Secure Authentication', 'Encrypted Communication', 'Offline Data Sync'],
    metrics: '100% Offline Support',
    category: 'enterprise',
    featured: true,
    role: 'Flutter Developer',
    teamSize: '2 developers',
    timeline: '5 months',
    businessDomain: 'Maritime',
    businessImpact: 'Digitized and secured maritime operational communications, reducing coordination overhead for marine industry enterprise clients.',
    problem: 'Maritime operations relied on fragmented, insecure communication channels with no offline capability — critical in environments with limited connectivity at sea.',
    solution: 'Built an encrypted communication platform with multi-layer authentication, offline-first data architecture, and secure synchronization when connectivity is restored.',
    architecture: 'Offline-first architecture with encrypted local storage, background sync service, and multi-layer authentication pipeline.',
    features: ['Secure Enterprise Communication', 'Maritime Workflow Management', 'Multi-Layer Authentication', 'Operational Data Sync', 'Offline Capability', 'Android & iOS Deployment'],
    challenges: [
      'Ensuring data security in compliance with maritime regulations',
      'Building reliable offline-first sync for extended connectivity gaps',
      'Multi-layer authentication without compromising user experience',
    ],
    results: [
      { metric: 'Security', value: 'Enterprise' },
      { metric: 'Offline Support', value: '100%' },
      { metric: 'Platforms', value: '2' },
    ],
    playStoreUrl: 'https://play.google.com/store/apps/details?id=com.instanceit.dgseaagent&hl=en_IN',
    appStoreUrl: 'https://apps.apple.com/in/app/dgferry-agent-booking-platform/id6499256780',
    floating: {
      size: 'wide',
      depth: 'front',
      laneTop: '36%',
      direction: 1,
      duration: 22,
      initialProgress: 0.88,
      floatAmp: 11,
      tilt: 0.7,
    },
  },
  {
    id: 'dg-sea-connect',
    index: '10',
    name: 'DG Sea Connect',
    title: 'DG Sea Connect',
    subtitle: 'Maritime Enterprise Communication',
    meta: '5 months · Secure · Play Store',
    coverImage: '/projects/dg-sea-connect.svg',
    shortDescription: 'Encrypted maritime communication platform with multi-layer authentication and real-time sync for offshore vessels with intermittent connectivity.',
    description:
      'Enterprise maritime communication platform with encrypted secure channels, multi-layer authentication, real-time operational data synchronization, and offline-first architecture for use at sea with limited connectivity.',
    stack: ['Flutter', 'REST API', 'Secure Auth', 'Encryption', 'Offline Sync'],
    metrics: 'Enterprise Security',
    category: 'enterprise',
    featured: true,
    role: 'Flutter Developer',
    teamSize: '2 developers',
    timeline: '5 months',
    businessDomain: 'Maritime',
    businessImpact: 'Digitized and secured maritime operational communications, reducing coordination overhead for marine industry enterprise clients.',
    problem: 'Maritime operations relied on fragmented, insecure communication channels with no offline capability.',
    solution: 'Built an encrypted communication platform with multi-layer authentication and offline-first data architecture.',
    architecture: 'Offline-first architecture with encrypted local storage, background sync service, and multi-layer authentication pipeline.',
    features: ['Secure Enterprise Communication', 'Maritime Workflow Management', 'Multi-Layer Authentication', 'Operational Data Sync', 'Offline Capability'],
    challenges: [
      'Ensuring data security in compliance with maritime regulations',
      'Building reliable offline-first sync for extended connectivity gaps',
    ],
    results: [
      { metric: 'Security', value: 'Enterprise' },
      { metric: 'Offline Support', value: '100%' },
    ],
    playStoreUrl: 'https://play.google.com/store/apps/details?id=com.instanceit.dgseaconnect&hl=en_IN',
    floating: {
      size: 'portrait',
      depth: 'far',
      laneTop: '60%',
      direction: -1,
      duration: 33,
      initialProgress: 0.15,
      floatAmp: 7,
      tilt: -0.6,
    },
  },
  {
    id: 'manier-de-voir',
    index: '11',
    name: 'Manier De Voir',
    title: 'Manier De Voir',
    subtitle: 'Premium Fashion E-Commerce',
    meta: '4 months · 4.5★ Rating · Play Store & App Store',
    coverImage: '/projects/manier-de-voir.svg',
    shortDescription: 'High-conversion luxury fashion mobile commerce app with advanced catalogs, dynamic filtering, Apple Pay, and 4.5★ rating.',
    description:
      'Premium fashion and lifestyle mobile commerce application delivering a high-conversion shopping experience with advanced product catalogs, dynamic filtering, Apple Pay, secure user authentication, and order lifecycle management.',
    stack: ['Flutter', 'REST API', 'Apple Pay', 'BLoC', 'OAuth', 'Push Notifications'],
    metrics: '4.5★ Rating · 1000+ Catalog Items',
    category: 'mobile',
    featured: true,
    role: 'Flutter Developer',
    teamSize: '2 developers',
    timeline: '4 months',
    businessDomain: 'Retail / Fashion',
    businessImpact: 'Delivered a premium shopping experience for a global fashion brand with full Play Store and App Store availability.',
    problem: 'A global fashion brand needed a native-feel mobile shopping experience with high-conversion product discovery and seamless checkout.',
    solution: 'Crafted a pixel-perfect e-commerce app with BLoC-driven product catalog, lazy-loaded image galleries, and a streamlined 3-step checkout flow integrated with secure payment gateways.',
    architecture: 'BLoC pattern for state management, repository pattern for API abstraction, image caching layer for performance, and modular feature architecture.',
    features: ['Advanced Product Catalog', 'Secure User Authentication', 'Order Lifecycle Management', 'Apple Pay Integration', 'Wishlist & Cart Management', 'Push Notifications'],
    challenges: [
      'Achieving brand-consistent UI with pixel-perfect design specifications',
      'Optimizing image-heavy catalog performance across devices',
      'Seamless multi-currency payment gateway integration',
    ],
    results: [
      { metric: 'Catalog Items', value: '1000+' },
      { metric: 'App Rating', value: '4.5★' },
      { metric: 'Platforms', value: '2' },
    ],
    playStoreUrl: 'https://play.google.com/store/apps/details?id=com.manieredevoirshop&hl=en_IN',
    appStoreUrl: 'https://apps.apple.com/us/app/mani%C3%A8re-de-voir/id6448750840',
    floating: {
      size: 'large',
      depth: 'front',
      laneTop: '64%',
      direction: -1,
      duration: 18,
      initialProgress: 0.68,
      floatAmp: 12,
      tilt: -1.0,
    },
  },
  {
    id: 'yoneti',
    index: '12',
    name: 'YONETI',
    title: 'YONETI',
    subtitle: 'Shop Management & Service Platform',
    meta: '5 months · Dual-Role · Android · iOS',
    coverImage: '/projects/yoneti.svg',
    shortDescription: 'Dual-role merchant & customer ecosystem that simplifies service booking, inventory, order processing, and customer notifications.',
    description:
      'Dual-role platform for customers and merchants that simplifies service booking, inventory management, customer support, notifications, and business operations — all in a single unified ecosystem.',
    stack: ['Flutter', 'Laravel', 'REST API', 'Riverpod', 'Push Notifications'],
    metrics: '+40% Efficiency',
    category: 'enterprise',
    featured: true,
    role: 'Flutter Developer',
    teamSize: '2 developers',
    timeline: '5 months',
    businessDomain: 'Retail',
    businessImpact: 'Streamlined shop operations and enhanced customer service booking experiences.',
    problem: 'Merchants needed an integrated system to manage inventory and services, while customers needed an easy way to book them.',
    solution: 'Developed a dual-role application offering comprehensive dashboards for merchants and an intuitive booking interface for customers.',
    architecture: 'Clean Architecture with Riverpod state management and robust API handling.',
    features: ['Merchant Dashboard', 'Customer App', 'Inventory Management', 'Order Processing', 'Service Booking', 'Push Notifications', 'Analytics'],
    challenges: [
      'Handling diverse user roles within a single ecosystem',
      'Synchronizing inventory in real-time',
    ],
    results: [
      { metric: 'Efficiency', value: '+40%' },
      { metric: 'Roles', value: 'Dual' },
    ],
    floating: {
      size: 'small',
      depth: 'middle',
      laneTop: '6%',
      direction: 1,
      duration: 27,
      initialProgress: 0.92,
      floatAmp: 8,
      tilt: 0.5,
    },
  },
];

export const moreProjects: MoreProject[] = [
  { name: 'Chrome Extension', detail: 'Browser Automation · JavaScript Bridge · DOM Manipulation' },
  { name: 'Flutter Desktop App', detail: 'Windows · macOS · System Integration · Offline Capabilities' },
  { name: 'AI Search Integration', detail: 'OpenAI · Semantic Search · Product Discovery' },
  { name: 'Voice Assistant App', detail: 'LLM API · Speech-to-Text · Flutter Mobile' },
  { name: 'Flutter PDF Generator', detail: 'Report Generation · Export · Dynamic Templates' },
  { name: 'Excel Import/Export Module', detail: 'Enterprise Data · Bulk Operations · Flutter' },
  { name: 'QR Scanner System', detail: 'Gate Management · Real-time Verification · Flutter' },
  { name: 'Bluetooth Printer SDK', detail: 'Hardware Integration · Custom Flutter Plugin' },
];

export const experiences: Experience[] = [
  {
    year: '2025',
    company: 'Cirkle Studio',
    role: 'Senior Flutter Developer\n& Technical Lead',
    domain: 'Digital Product Studio',
    duration: 'Aug 2025 – Present',
    current: true,
    color: '#E31E24',
    bullets: [
      'Lead architecture of enterprise cross-platform apps using Clean Architecture + MVVM across Android, iOS, Web, and Desktop',
      'Mentor 4 Flutter developers, built reusable component library shared across 5+ active projects',
      'Reduced app startup time by 45% via lazy initialization & widget tree optimization',
      'CI/CD via GitHub Actions + Fastlane — 60% reduction in deployment cycles',
      'Client communication, stakeholder management, and Agile sprint planning',
    ],
    stack: ['Flutter', 'Dart', 'Firebase', 'GitHub Actions', 'Fastlane', 'Clean Architecture', 'BLoC', 'Provider'],
    responsibilities: [
      'Technical Team Leadership & Mentoring',
      'Enterprise Application Architecture (Clean Architecture, MVVM)',
      'Flutter Web & Desktop Application Development',
      'Firebase, REST API, Third-Party API & SDK Integration',
      'CI/CD Pipeline Implementation (GitHub Actions, Fastlane)',
      'Application Performance Optimization & Security',
      'Client Communication & Stakeholder Management',
    ],
    achievements: [
      'Architected reusable component library used across 5+ projects',
      'Reduced app startup time by 45% through lazy loading & tree shaking',
      'Implemented CI/CD pipelines reducing deployment time by 60%',
    ],
    metrics: [
      { label: 'Team Size', value: '4+' },
      { label: 'Projects', value: '5+' },
      { label: 'Startup Time', value: '-45%' },
      { label: 'Deploy Speed', value: '-60%' },
    ],
  },
  {
    year: '2024',
    company: 'Instance IT Solutions',
    role: 'Flutter Developer',
    domain: 'Enterprise Software',
    duration: 'Jun 2024 – Aug 2025',
    current: false,
    color: '#a0a0a0',
    bullets: [
      'Built Magicrete BuildMart — 100K+ Play Store downloads, offline-first SQLite architecture',
      'Shipped 6 production apps: ZingHR, DG Ferry, DG Sea Connect, Magicrete Sarthak, Pulpit Mobility, SAH INVESTMENT',
      'Integrated 3+ enterprise ERP/CRM systems with background sync + delta-update logic',
      'Reduced REST API data consumption by 40% via caching, pagination, deduplication',
      'Payment gateway integration: Razorpay, PhonePe, Apple Pay across multiple apps',
    ],
    stack: ['Flutter', 'REST API', 'ERP Integration', 'SQLite', 'Payment Gateways', 'WebSocket', 'Fastlane'],
    responsibilities: [
      'Enterprise CRM & ERP Integration',
      'Play Store & App Store Deployment (Fastlane, CI/CD)',
      'Payment Gateway & Third-Party API Integration',
      'Offline Data Synchronization Architecture',
      'Cross-Platform Application Development (Android, iOS)',
      'Business Workflow Automation & Reporting Dashboards',
    ],
    achievements: [
      'Shipped Magicrete BuildMart to 100K+ downloads on Play Store',
      'Built offline-first architecture for low-connectivity construction zones',
      'Integrated 3+ enterprise ERP/CRM systems end-to-end',
      'Optimized API calls reducing data usage by 40%',
    ],
    metrics: [
      { label: 'Downloads', value: '100K+' },
      { label: 'ERP Systems', value: '3+' },
      { label: 'Data Usage', value: '-40%' },
    ],
  },
  {
    year: '2022',
    company: 'Webito Infotech',
    role: 'Flutter Developer',
    domain: 'IT Solutions Provider',
    duration: 'Jun 2022 – Jun 2024',
    current: false,
    color: '#a0a0a0',
    bullets: [
      'Delivered 10+ cross-platform mobile apps across recruitment, real estate, e-commerce, and enterprise',
      'Architected MyRCloud — multi-platform ecosystem serving 5K+ candidates with HRMS + WebSocket + RBAC',
      'Reduced crash rate by 85% via Crashlytics monitoring and structured error handling',
      'Integrated GraphQL APIs for real-time data-heavy property management platforms',
      'State management across BLoC, Provider, and Riverpod depending on project needs',
    ],
    stack: ['Flutter', 'GraphQL', 'REST API', 'Provider', 'BLoC', 'Riverpod', 'Firebase', 'Flutter Web'],
    responsibilities: [
      'Cross-Platform Mobile Application Development',
      'GraphQL & REST API Integration',
      'Job Portal & Recruitment Platform Development',
      'State Management (Provider, BLoC, Riverpod)',
      'Real Estate & Property Management Applications',
      'Application Performance Optimization',
    ],
    achievements: [
      'Delivered 10+ production apps across diverse industry domains',
      'Reduced crash rate by 85% through systematic error handling',
      'Built recruitment platform serving 5K+ active candidates',
      'Mastered 3 state management approaches (Provider, BLoC, Riverpod)',
    ],
    metrics: [
      { label: 'Apps Shipped', value: '10+' },
      { label: 'Crash Rate', value: '-85%' },
      { label: 'Users Served', value: '5K+' },
    ],
  },
  {
    year: '2019',
    company: 'VI Store',
    role: 'Store Manager',
    domain: 'Retail Operations',
    duration: 'Apr 2019 – Jun 2022',
    current: false,
    color: '#444',
    bullets: [
      'Managed end-to-end retail operations for a consumer electronics & telecom outlet',
      'Led team of 8+ staff members and streamlined inventory processes',
      'Customer relationship management and stakeholder communication',
    ],
    stack: ['Retail Operations', 'CRM', 'Team Management', 'Inventory'],
    metrics: [
      { label: 'Team', value: '8+' },
    ],
  },
  {
    year: '2018',
    company: '7 Star Infotech',
    role: 'Android Developer',
    domain: 'Mobile Development',
    duration: 'Aug 2018 – Feb 2019',
    current: false,
    color: '#555',
    bullets: [
      'Built 3+ native Android applications using Java and Kotlin',
      'REST API integration and custom XML UI layouts',
      'Established mobile development fundamentals that led to Flutter specialization',
    ],
    stack: ['Java', 'Kotlin', 'Android SDK', 'REST API', 'XML Layouts'],
    metrics: [
      { label: 'Apps Built', value: '3+' },
    ],
  },
];

export const engineeringExpertise: EngineeringExpertise[] = [
  {
    title: 'Flutter Engineering',
    tagline: 'One codebase. Every platform. Zero compromise.',
    technologies: ['Flutter', 'Dart', 'Android', 'iOS', 'Web', 'Desktop', 'Chrome Extensions'],
    proofBadge: '30+ Production Apps Shipped',
  },
  {
    title: 'Enterprise Application Development',
    tagline: 'Mission-critical applications built for scale, compliance, and real users.',
    technologies: ['ERP Integration', 'HRMS', 'Construction Marketplace', 'Multi-Branch Systems', 'POS Systems'],
    proofBadge: 'Enterprise Production Delivered',
  },
  {
    title: 'Cross-Platform Architecture',
    tagline: 'Scalable patterns that make codebases maintainable at scale.',
    technologies: ['Clean Architecture', 'MVVM', 'BLoC', 'Riverpod', 'Provider', 'Shared Codebase'],
    proofBadge: 'Enterprise Codebases Maintained',
  },
  {
    title: 'Desktop Application Development',
    tagline: 'Native-feel desktop intelligence for Windows and macOS.',
    technologies: ['Flutter Windows', 'Flutter macOS', 'System Integration', 'Offline Capabilities', 'GraphQL'],
    proofBadge: 'Desktop Platforms Deployed',
  },
  {
    title: 'Backend & Cloud Integration',
    tagline: 'Scalable APIs and real-time infrastructure at enterprise scale.',
    technologies: ['Firebase', 'REST API', 'GraphQL', 'WebSocket', 'AWS', 'Supabase', 'Azure Integration'],
    proofBadge: '15+ Integrations Delivered',
  },
  {
    title: 'AI Integration & Automation',
    tagline: 'Intelligent capabilities integrated into real workflows.',
    technologies: ['OpenAI', 'Gemini', 'Claude', 'LLM APIs', 'Voice Assistants', 'OCR', 'Face Verify', 'Virtual Try-On'],
    proofBadge: 'Production AI Workflows Built',
  },
  {
    title: 'Mobile Commerce & Payments',
    tagline: 'Secure, high-conversion shopping and POS experiences.',
    technologies: ['Razorpay', 'PhonePe', 'Apple Pay', 'Payment Gateway Integration', 'E-commerce', 'POS'],
    proofBadge: 'High-Volume Transactions',
  },
  {
    title: 'CI/CD & DevOps',
    tagline: 'Automated pipelines that ship code fast and safely.',
    technologies: ['GitHub Actions', 'Fastlane', 'Codemagic', 'App Store Deploy', 'Play Store Deploy', 'Automated Testing'],
    proofBadge: '60% Faster Deployment',
  },
  {
    title: 'Technical Team Leadership',
    tagline: 'Guiding cross-functional teams to deliver exceptional products.',
    technologies: ['Architecture Decisions', 'Code Review', 'Agile Scrum', 'Mentoring', 'Sprint Planning', 'Client Communication'],
    proofBadge: 'Led 4+ Developers',
  },
];

export const aiCapabilities = [
  { label: 'AI Search', icon: '🔍' },
  { label: 'AI API Integration', icon: '🔗' },
  { label: 'Image Processing', icon: '🖼️' },
  { label: 'OCR Extraction', icon: '📄' },
  { label: 'Voice Assistant', icon: '🎙️' },
  { label: 'Face Verification', icon: '👤' },
  { label: 'Virtual Try-On', icon: '👔' },
  { label: 'AI Automation', icon: '⚡' },
  { label: 'LLM Integration', icon: '🤖' },
  { label: 'AI-Assisted Dev', icon: '💻' },
];

export const aiTools = [
  { label: 'OpenAI', category: 'LLM' },
  { label: 'Gemini', category: 'LLM' },
  { label: 'Claude', category: 'LLM' },
  { label: 'Google Cloud', category: 'Cloud' },
  { label: 'Cloudflare AI', category: 'Edge' },
  { label: 'Firebase ML', category: 'ML' },
  { label: 'Vertex AI', category: 'ML' },
  { label: 'Cursor', category: 'Dev Tool' },
  { label: 'Antigravity', category: 'Dev Tool' },
  { label: 'Blackbox AI', category: 'Dev Tool' },
];

export const skillNodes: SkillNode[] = [
  { label: 'Flutter', x: 50, y: 30, size: 1.4, depth: 0, category: 'core' },
  { label: 'Dart', x: 30, y: 50, size: 1.1, depth: 1, category: 'core' },
  { label: 'Android', x: 70, y: 22, size: 1.0, depth: 1, category: 'mobile' },
  { label: 'iOS', x: 20, y: 32, size: 1.0, depth: 1, category: 'mobile' },
  { label: 'Flutter Web', x: 78, y: 58, size: 0.9, depth: 1, category: 'mobile' },
  { label: 'BLoC', x: 82, y: 42, size: 0.9, depth: 2, category: 'arch' },
  { label: 'Clean Arch', x: 15, y: 65, size: 0.9, depth: 2, category: 'arch' },
  { label: 'Riverpod', x: 60, y: 68, size: 0.85, depth: 2, category: 'arch' },
  { label: 'Provider', x: 35, y: 70, size: 0.8, depth: 2, category: 'arch' },
  { label: 'Firebase', x: 40, y: 78, size: 1.0, depth: 1, category: 'cloud' },
  { label: 'FCM', x: 52, y: 88, size: 0.75, depth: 2, category: 'cloud' },
  { label: 'Google Cloud', x: 25, y: 82, size: 0.8, depth: 2, category: 'cloud' },
  { label: 'REST API', x: 84, y: 70, size: 0.9, depth: 2, category: 'api' },
  { label: 'GraphQL', x: 10, y: 80, size: 0.8, depth: 3, category: 'api' },
  { label: 'WebSocket', x: 75, y: 85, size: 0.85, depth: 2, category: 'api' },
  { label: 'OpenAI', x: 25, y: 15, size: 0.9, depth: 1, category: 'ai' },
  { label: 'Gemini', x: 60, y: 10, size: 0.85, depth: 2, category: 'ai' },
  { label: 'Claude', x: 88, y: 18, size: 0.8, depth: 2, category: 'ai' },
  { label: 'GitHub Actions', x: 45, y: 92, size: 0.8, depth: 3, category: 'cicd' },
  { label: 'Fastlane', x: 12, y: 45, size: 0.75, depth: 3, category: 'cicd' },
  { label: 'SQLite', x: 88, y: 35, size: 0.8, depth: 2, category: 'db' },
  { label: 'Node.js', x: 35, y: 20, size: 0.85, depth: 2, category: 'backend' },
  { label: 'TypeScript', x: 65, y: 92, size: 0.75, depth: 3, category: 'lang' },
  { label: 'Java', x: 90, y: 78, size: 0.7, depth: 3, category: 'lang' },
  { label: 'Razorpay', x: 5, y: 20, size: 0.75, depth: 3, category: 'payments' },
  { label: 'Biometrics', x: 95, y: 55, size: 0.75, depth: 3, category: 'security' },
  { label: 'Encryption', x: 5, y: 55, size: 0.75, depth: 3, category: 'security' },
  { label: 'Crashlytics', x: 78, y: 12, size: 0.7, depth: 3, category: 'cicd' },
];

export const hardwareIntegration: HardwareSkill[] = [
  { label: 'Biometric Authentication', icon: '🔒', category: 'Security' },
  { label: 'Face Verification', icon: '👁️', category: 'Security' },
  { label: 'Bluetooth Printer', icon: '🖨️', category: 'Device' },
  { label: 'Card Swiper / Reader', icon: '💳', category: 'Device' },
  { label: 'QR Code Scanner', icon: '📷', category: 'Camera' },
  { label: 'Barcode Scanner', icon: '📊', category: 'Camera' },
  { label: 'Android TV', icon: '📺', category: 'Platform' },
  { label: 'Smart Home Devices', icon: '🏠', category: 'IoT' },
  { label: 'Platform Channels', icon: '🔧', category: 'Native' },
  { label: 'Hardware SDK Integration', icon: '⚙️', category: 'Native' },
  { label: 'Device Permissions', icon: '🛡️', category: 'Native' },
  { label: 'Camera Integration', icon: '📸', category: 'Camera' },
];

export const services: Service[] = [
  {
    title: 'Enterprise Flutter Development',
    description: 'Architecting and delivering enterprise-grade cross-platform mobile applications for Android and iOS with Clean Architecture, state management, and scalable codebase design.',
    icon: '📱',
    stat: '30+ Apps Delivered',
    features: ['Clean Architecture & MVVM', 'Cross-platform Android & iOS', 'State Management (BLoC, Riverpod)', 'Scalable modular codebase'],
  },
  {
    title: 'Flutter Web & Desktop',
    description: 'Building high-performance web and Windows Desktop applications using Flutter, enabling single-codebase solutions across all target platforms for enterprise clients.',
    icon: '💻',
    stat: '4 Platforms Covered',
    features: ['Responsive web applications', 'Windows Desktop deployment', 'Single shared codebase', 'Platform-adaptive UI'],
  },
  {
    title: 'Firebase & Cloud Integration',
    description: 'Full-stack Firebase integration including Authentication, Firestore, Cloud Functions, FCM Push Notifications, Analytics, and cloud services.',
    icon: '☁️',
    stat: '99.9% Uptime',
    features: ['Authentication & Firestore', 'Cloud Functions & FCM', 'Analytics & Crashlytics', 'AWS S3/SNS integration'],
  },
  {
    title: 'API & Enterprise Integration',
    description: 'End-to-end REST API, GraphQL, WebSocket, ERP, CRM, and HRMS integrations with robust error handling, offline synchronization, and scalable data architecture.',
    icon: '🔌',
    stat: '15+ Integrations',
    features: ['REST & GraphQL APIs', 'WebSocket real-time data', 'ERP/CRM/HRMS bridges', 'Offline-first sync'],
  },
  {
    title: 'CI/CD & DevOps',
    description: 'Implementing CI/CD pipelines using GitHub Actions and Fastlane for automated testing, building, and deployment to Google Play Store and Apple App Store.',
    icon: '🚀',
    stat: '60% Faster Deploys',
    features: ['GitHub Actions pipelines', 'Fastlane automation', 'Automated testing & builds', 'Store deployment automation'],
  },
  {
    title: 'Performance Optimization',
    description: 'Deep performance profiling, memory optimization, rendering optimization, and build size reduction to deliver production-grade, high-performance applications.',
    icon: '⚡',
    stat: '45% Faster Startup',
    features: ['Memory & CPU profiling', 'Rendering optimization', 'Build size reduction', 'Lazy loading strategies'],
  },
  {
    title: 'Payment & Security',
    description: 'Implementing secure payment gateway integrations (Razorpay, PhonePe, Apple Pay), OAuth authentication, biometric security, and enterprise-grade mobile security protocols.',
    icon: '🔒',
    stat: 'Enterprise Grade',
    features: ['Razorpay, PhonePe, Apple Pay', 'Biometric authentication', 'Encryption & data security', 'OAuth & social login'],
  },
  {
    title: 'Technical Leadership',
    description: 'Providing technical leadership including solution architecture design, code reviews, sprint planning, team mentoring, and stakeholder management for complex software projects.',
    icon: '👥',
    stat: 'Led 4+ Developers',
    features: ['Solution architecture design', 'Code reviews & mentoring', 'Sprint planning & Scrum', 'Stakeholder management'],
  },
];

export const testimonials: Testimonial[] = [
  {
    name: 'Rajesh Patel',
    role: 'CEO',
    company: 'TechVentures Inc.',
    content: 'Chirag delivered an exceptional mobile application that exceeded our expectations. His attention to detail and understanding of UI/UX principles made our product stand out in the market. Highly recommended for any Flutter project.',
    rating: 5.0,
    initials: 'RP',
    accentColor: '#4F46E5',
  },
  {
    name: 'Priya Sharma',
    role: 'Product Manager',
    company: 'InnovateTech Solutions',
    content: 'Working with Chirag was a pleasure. He transformed our complex requirements into a beautiful, intuitive app. His expertise in Flutter and Firebase made the development process smooth and efficient.',
    rating: 5.0,
    initials: 'PS',
    accentColor: '#7C3AED',
  },
  {
    name: 'Michael Chen',
    role: 'CTO',
    company: 'GlobalApp Studios',
    content: "Chirag's deep understanding of clean architecture and state management patterns resulted in a highly maintainable codebase. He consistently delivers quality work on time.",
    rating: 5.0,
    initials: 'MC',
    accentColor: '#06B6D4',
  },
  {
    name: 'Anita Desai',
    role: 'Founder',
    company: 'StartupHub',
    content: 'From concept to deployment, Chirag handled our entire mobile strategy. His cross-platform expertise saved us significant development time and costs while maintaining native-level quality.',
    rating: 5.0,
    initials: 'AD',
    accentColor: '#10B981',
  },
  {
    name: 'David Wilson',
    role: 'Tech Lead',
    company: 'Enterprise Solutions Co.',
    content: "Chirag's ability to handle complex UI animations and responsive layouts is remarkable. He brought our design vision to life with pixel-perfect precision across all platforms.",
    rating: 5.0,
    initials: 'DW',
    accentColor: '#F59E0B',
  },
];

export const highlights: Highlight[] = [
  {
    icon: '🚀',
    title: 'Published Enterprise Applications',
    description: 'Successfully architected and published 8+ mobile applications on Google Play Store and Apple App Store, serving real users across transportation, construction, HR, fashion, and maritime industries.',
    stat: '8+',
  },
  {
    icon: '👥',
    title: 'Technical Team Leadership',
    description: 'Led cross-functional Flutter development teams, facilitated Agile Scrum sprint planning and retrospectives, conducted systematic code reviews, and mentored junior developers on Clean Architecture principles.',
    stat: '4+',
  },
  {
    icon: '📱',
    title: 'True Cross-Platform Delivery',
    description: 'Delivered production-grade applications across all Flutter target platforms: Android, iOS, Web, and Windows Desktop, maintaining a consistent, scalable codebase across all environments.',
    stat: '4',
  },
  {
    icon: '☁️',
    title: 'Enterprise Cloud & API Integrations',
    description: 'Built end-to-end integrations with Firebase, AWS S3/SNS, REST APIs, GraphQL, Payment Gateways, ERP, CRM, and HRMS systems to power enterprise-grade business workflows.',
    stat: '15+',
  },
  {
    icon: '📈',
    title: '100K+ Downloads Milestone',
    description: 'Engineered Magicrete BuildMart to a 100K+ download milestone on Google Play Store, optimizing offline data synchronization for construction marketplace operations in low-connectivity environments.',
    stat: '100K+',
  },
  {
    icon: '⚙️',
    title: 'CI/CD & DevOps Implementation',
    description: 'Implemented automated CI/CD pipelines using GitHub Actions and Fastlane for end-to-end build, test, and deployment automation to Google Play Store and Apple App Store.',
    stat: '60%',
  },
];

export const navItems = [
  { num: '01', label: 'Home', href: '#hero' },
  { num: '02', label: 'About', href: '#about' },
  { num: '03', label: 'Skills', href: '#skills' },
  { num: '04', label: 'Work', href: '#projects' },
  { num: '05', label: 'Experience', href: '#experience' },
  { num: '06', label: 'AI', href: '#ai' },
  { num: '07', label: 'Services', href: '#services' },
  { num: '08', label: 'Highlights', href: '#highlights' },
  { num: '09', label: 'Contact', href: '#contact' },
];
